spring:
  application:
    name: mozu
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://db:3306/moju_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "test_id"
            client-secret: "test_secret"
            scope:
              - email
              - profile

jwt:
  secret: thisIsATestSecretKeyForLocalDevelopment123456
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        # 이 부분이 없으면 프로메테우스 데이터를 밖으로 꺼내주지 않습니다.
        include: "prometheus,info,health,metrics"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always